

import { Flex, Box, Text, InputGroup, InputRightElement, Image, Button, Heading, Stack, Input, Divider, AbsoluteCenter, FormLabel, Link } from "@chakra-ui/react";

export default function CookieConsent(){
    return (
      

            <Flex alignItems="center" justifyContent="center"  flexDirection="column" h={900} w={1000} backgroundColor='#FFF3F3' borderColor="#837A7A" mx="auto" mb={20}>

                <Box  w={900} display="flex" flexDirection="column" alignItems="left" justifyContent="center">              
                    <h1  text-xl className='flex flex-col items-center'>Privacy Policy</h1>
                    <Text fontSize="16" fontFamily='Open Sans, sans-serif' fontWeight={400} mr={30} mt={10} mb={20}> This Privacy Policy describes how Epic Cafe ("we," "us," or "our") collects, uses,
                     and discloses your personal information when you visit our website ("Site") and use the services provided. By accessing or using the Site, you agree to the terms of this Privacy Policy.</Text>   
                    
                    <h2>1. Information We Collect </h2>
                     <p>Google Analytics: We use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to analyze your use of the Site. The information generated by the cookie about your use of the Site (including your IP address) will be transmitted to and stored by Google on servers in the United States.</p>
                
                     <h2>2. Use of Information</h2>

                    <p>We use the information collected through Google Analytics to analyze user behavior and improve the user experience on our Site.</p>
                    <h2>3. Google Analytics and Cookies</h2>

                    <p>Google Analytics employs cookies to track user interactions. These cookies are used to store information, such as the time of your visit, whether you have visited the Site before, and the website that referred you to our Site.</p>
                    <h2>4. Consent to Use Cookies</h2>

                    <p>By using our Site, you consent to the use of cookies, including those used by Google Analytics.</p>
                    <h2>5. Opt-Out of Google Analytics</h2>

                    <p>You can opt-out of Google Analytics by using the Google Analytics Opt-out Browser Add-on, available at https://tools.google.com/dlpage/gaoptout.
                    </p>

                    <h2>6. Your Rights</h2>

                    <p>Under the General Data Protection Regulation (GDPR), you have the right to access, rectify, or erase your personal data. To exercise these rights, please contact us at [epiccafe0@hotmail.com].
                    </p>
                    <h2>7. Changes to this Privacy Policy</h2>

                    <p>We may update this Privacy Policy to reflect changes in our practices. We encourage you to review this page periodically for the latest information on our privacy practices.</p>

                    <h2>8. Contact Information</h2>

                    <p>If you have any questions or concerns about our Privacy Policy, please contact us at [epiccafe0@hotmail.com].</p>
                                    
                </Box>

            

            </Flex>
     
        
    )
}