

export default function CookieConsent(){
    return (
        <div>
        <h1>Privacy Policy</h1>
        <p>


This Privacy Policy describes how Epic Cafe ("we," "us," or "our") collects, uses, and discloses your personal information when you visit our website ("Site") and use the services provided. By accessing or using the Site, you agree to the terms of this Privacy Policy.

1. Information We Collect

Google Analytics: We use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to analyze your use of the Site. The information generated by the cookie about your use of the Site (including your IP address) will be transmitted to and stored by Google on servers in the United States.
2. Use of Information

We use the information collected through Google Analytics to analyze user behavior and improve the user experience on our Site.
3. Google Analytics and Cookies

Google Analytics employs cookies to track user interactions. These cookies are used to store information, such as the time of your visit, whether you have visited the Site before, and the website that referred you to our Site.
4. Consent to Use Cookies

By using our Site, you consent to the use of cookies, including those used by Google Analytics.
5. Opt-Out of Google Analytics

You can opt-out of Google Analytics by using the Google Analytics Opt-out Browser Add-on, available at https://tools.google.com/dlpage/gaoptout.
6. Your Rights

Under the General Data Protection Regulation (GDPR), you have the right to access, rectify, or erase your personal data. To exercise these rights, please contact us at [epiccafe0@hotmail.com].
7. Changes to this Privacy Policy

We may update this Privacy Policy to reflect changes in our practices. We encourage you to review this page periodically for the latest information on our privacy practices.
8. Contact Information

If you have any questions or concerns about our Privacy Policy, please contact us at [epiccafe0@hotmail.com].
        </p>    
        </div>
    )
}
